apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-component-git-source-cxwu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-component-git-source-cxwu
    app.kubernetes.io/part-of: build-suite-test-application-pzcz
  name: build-suite-test-component-git-source-cxwu
  namespace: appstudio-e2e-test
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: build-suite-test-component-git-source-cxwu
    weight: 100
status: {}
